export const SUBMIT_TRANSACTION_REQUEST = 'transaction-request/SUBMIT_TRANSACTION_REQUEST';
export const SUBMIT_TRANSACTION_REQUEST_SUCCESS = 'transaction-request/SUBMIT_TRANSACTION_REQUEST_SUCCESS';
export const SUBMIT_TRANSACTION_REQUEST_FAILURE = 'transaction-request/SUBMIT_TRANSACTION_REQUEST_FAILURE';

export const FETCH_TRANSACTIONS = 'transaction/FETCH_TRANSACTIONS';
export const FETCH_TRANSACTIONS_SUCCESS = 'transaction/FETCH_TRANSACTIONS_SUCCESS';
export const FETCH_TRANSACTIONS_FAILURE = 'transaction/FETCH_TRANSACTIONS_FAILURE';
